New button and page created for affiliate projects
OpenDataScienceLab/blog pull request #1
Opened 2019-08-23 13:26 UTC by esloch

--New button and page created for affiliate projects.

2019-08-23 13:28 UTC, esloch commented
![Screenshot_20190823_101612](https://user-images.githubusercontent.com/3450741/63596034-b7230980-c590-11e9-9889-e4cf2d0afb26.png)

2019-08-23 14:32 UTC, xmnlab commented on output/pages/childrenprojects/index.html
> +############################################################################################
alll these projects here could be removed. just keep skdata and ajna

2019-08-23 14:34 UTC, xmnlab requested changes
@esloch I just added some notes about something you should change.
about the name, change also the name of the folder from "childrenprojects" to "affiliated_projects"

2019-08-23 18:36 UTC, esloch reviewed
It will be done!
Thanks.

2019-08-23 18:36 UTC, esloch commented on output/pages/childrenprojects/index.html
> +############################################################################################
-  Skdata and Ajnaprojects will be kept!
- More info: Add Access Links to projects.
- Create a PopUp on the page on how to access the requirements to be an affiliate project.

2019-08-23 21:11 UTC, xmnlab commented
I think the `cache` folder shouldn't be stored into the repo.

2019-08-23 22:18 UTC, esloch commented
-- I will provide a .gitignore; Any other files?

2019-08-23 23:08 UTC, xmnlab commented
also ` __pycach__`

2019-08-29 13:31 UTC, xmnlab approved these changes

2019-08-29 13:31 UTC, merged